/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.kosso.tiandroidaudioplayer;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;


@Kroll.module(name="Tiandroidaudioplayer", id="com.kosso.tiandroidaudioplayer")
public class TiandroidaudioplayerModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TiandroidaudioplayerModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	//@Kroll.constant public static final String EXTERNAL_NAME = "My Awesome Android Module";

	public TiandroidaudioplayerModule(TiContext tiContext)
	{
		super(tiContext);
		
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}


}

